### ISSUE TITLE
Problème de lancement du serveur Hugo après le clone du template

### ISSUE THREAD

**Issue by sachaandre** [noesya/osuny-hugo-template-aaa#3]
En suivant le démarrage rapide (https://developers.osuny.org/docs/website/demarrage-rapide/) , et sur un Mac tout neuf, j'arrive sur une erreur en lançant `hugo server` pour la première fois.

J'arrive sur cette erreur :
```
Error: command error: failed to create config from result: failed to decode "languages": config value "en" for defaultContentLanguage does not match any language definition
```

Est-ce lié à un problème d'installation de hugo de ma part où est-ce un autre problème ?

NB : la commande `yarn dev` me sort la même erreur

**Comment by arnaudlevy** [comment]
Salut Sacha !

C'est à cause des fichiers de config @pabois, il faudrait enregistrer ton site dans Osuny pour les régénérer clean

**Comment by sachaandre** [comment]
Ducoup j'ai changé ma configuration en rajoutant `defaultContentLanguage: fr` dans `config.yaml`
Tout fonctionne de mon côté !

**Comment by SebouChu** [comment]
Merci Sacha! Je viens de mettre à jour le template avec les configs par défaut générés par le back-office ! Je ferme !
